"""changed dungeon_type key

Revision ID: 0dade89d97ee
Revises: 228c6302efcc
Create Date: 2023-10-02 11:20:48.473055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dade89d97ee'
down_revision = '228c6302efcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dungeon_id', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_monsters_dungeon_type_dungeons', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_monsters_dungeon_id_dungeons'), 'dungeons', ['dungeon_id'], ['id'])
        batch_op.drop_column('dungeon_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dungeon_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_monsters_dungeon_id_dungeons'), type_='foreignkey')
        batch_op.create_foreign_key('fk_monsters_dungeon_type_dungeons', 'dungeons', ['dungeon_type'], ['type'])
        batch_op.drop_column('dungeon_id')

    # ### end Alembic commands ###
