"""added Monster, Dungeon, and updated character

Revision ID: 228c6302efcc
Revises: d465237fa6e1
Create Date: 2023-10-01 13:58:44.268730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228c6302efcc'
down_revision = 'd465237fa6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('def_', sa.Integer(), nullable=False),
    sa.Column('dungeon_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dungeon_type'], ['dungeons.type'], name=op.f('fk_monsters_dungeon_type_dungeons')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('atk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('_def', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('_def')
        batch_op.drop_column('atk')
        batch_op.drop_column('hp')

    op.drop_table('monsters')
    op.drop_table('dungeons')
    # ### end Alembic commands ###
