"""added Situation table

Revision ID: 728dfb652935
Revises: 98fd610a4f5b
Create Date: 2023-10-08 11:01:24.322467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728dfb652935'
down_revision = '98fd610a4f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('choice_1', sa.String(), nullable=False),
    sa.Column('choice_2', sa.String(), nullable=False),
    sa.Column('choice_3', sa.String(), nullable=False),
    sa.Column('choice_4', sa.String(), nullable=False),
    sa.Column('dungeon_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dungeon_id'], ['dungeons.id'], name=op.f('fk_situations_dungeon_id_dungeons')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('situations')
    # ### end Alembic commands ###
