"""changed dungeon_type key

Revision ID: c980efefb227
Revises: f0d9a4d75cfe
Create Date: 2023-10-02 20:08:05.378037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c980efefb227'
down_revision = 'f0d9a4d75cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('_def')
        batch_op.drop_column('hp')
        batch_op.drop_column('atk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atk', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hp', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('_def', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
