"""add character

Revision ID: d465237fa6e1
Revises: 63d0bffe9148
Create Date: 2023-09-29 18:44:50.356275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd465237fa6e1'
down_revision = '63d0bffe9148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('str', sa.Integer(), nullable=False),
    sa.Column('agi', sa.Integer(), nullable=False),
    sa.Column('vit', sa.Integer(), nullable=False),
    sa.Column('int', sa.Integer(), nullable=False),
    sa.Column('dex', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
